/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.spaceinvaders;

import org.junit.Test;
import static org.junit.Assert.*;

public class Test1 {
    @Test public void freebie() {
        // This test is a freebie, it should always pass
        assertTrue(true);
    }
}
